
#MEGABOSSES@42Porto

apiVersion: v1
kind: Service
metadata:
  name: micro-svc-service
spec:
  type: LoadBalancer
  selector:
    app: micro-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
