
#MEGABOSSES@42Porto

apiVersion: v1
kind: Service
metadata:
  name: my-static-website
spec:
  type: LoadBalancer #or Nodeport
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-static-website
