
#MEGABOSSES@42Porto

apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-hospital
  template:
    metadata:
      labels:
        app: website-hospital
    spec:
      containers:
      - name: website-hospital
        image: gcr.io/hacka-426822/hospv001gke:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
